name: Publish VS Marketplace

inputs:
  node-version:
    description: Node.js version
  package-name:
    description: Package name
  vs-marketplace-token:
    description: VS Marketplace tocken

runs:
  using: composite
  steps:
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: 'https://registry.npmjs.org'

    - name: Publish to Visual Studio Marketplace
      uses: HaaLeo/publish-vscode-extension@v1
      with:
        pat: ${{ inputs.vs-marketplace-token }}
        registryUrl: https://marketplace.visualstudio.com
        packagePath: ./packages/${{ inputs.package-name }}
