name: Run Tests

inputs:
  node-version:
    description: Node.js version

runs:
  using: composite
  steps:
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install dependencies
      shell: bash
      run: npm ci

    - name: Update playwright
      shell: bash
      run: npx playwright install --with-deps

    - name: Create builds
      shell: bash
      run: npm run build --workspaces --if-present # build all packages

    - name: Run package tests
      shell: bash
      run: npm test
