name: Release Commit

inputs:
  package-dir:
    description: Package directory
    required: true
  commit-msg:
    description: Commit Message
    required: false

runs:
  using: composite
  steps:
    - name: Set user
      shell: bash
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Modify .bumpfile
      shell: bash
      run: echo $RANDOM > packages/${{ inputs.package-dir }}/.bumpfile

    - name: Git commit
      shell: bash
      run: |
        git commit -am "release: ${{ inputs.commit-msg || 'manual release' }}"

    - name: Push to repo
      shell: bash
      run: git push origin main
