# allows to trigger release-please manually by modifying the .bumpfile for selected package
name: .bumpfile

on:
  workflow_dispatch:
    inputs:
      package:
        type: choice
        description: 'Package to bump'
        required: true
        options:
          - minze
          - create-minze
          - minze-vscode
          - '@minzejs/elements'
          - '@minzejs/vite-plugin-minze'
      commit-msg:
        type: string
        description: 'Commit message for release'

env:
  PACKAGE_NAME: ${{ github.event.inputs.package }}
  PACKAGE_DIR: ${{ (
    contains(github.event.inputs.package, '@minzejs/elements') && 'minze-elements' ||
    contains(github.event.inputs.package, '@minzejs/vite-plugin-minze') && 'vite-plugin-minze' ||
    github.event.inputs.package
    ) }}
  COMMIT_MSG: ${{ github.event.inputs.commit-msg }}

jobs:
  create-release-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create commit
        uses: ./.github/actions/create-release-commit
        with:
          package-dir: ${{ env.PACKAGE_DIR }}
          commit-msg: ${{ env.COMMIT_MSG }}
