name: Release

on:
  push:
    branches:
      - main
    paths:
      - 'packages/**'
      - 'package.json'
      - '!**/README.md'
  workflow_run:
    workflows:
      - .bumpfile
    branches:
      - main
    types:
      - completed
  workflow_dispatch:

env:
  NODE_VERSION: 20

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
    outputs:
      releases-created: ${{ steps.release.outputs.releases_created }}
      package-name: ${{ (
        (steps.release.outputs['packages/create-minze--release_created'] && 'create-minze') ||
        (steps.release.outputs['packages/minze--release_created'] && 'minze') ||
        (steps.release.outputs['packages/minze-vscode--release_created'] && 'minze-vscode') ||
        (steps.release.outputs['packages/vite-plugin-minze--release_created'] && 'vite-plugin-minze')
        ) }}

  bump-lockfile:
    needs:
      - release-please
    runs-on: ubuntu-latest
    if: ${{ needs.release-please.outputs.releases-created }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main # needs to be explicitly set to pull the latest changes

      - name: Bump lock file
        uses: ./.github/actions/bump-lockfile
        with:
          node-version: ${{ env.NODE_VERSION }}

  publish-npm:
    needs:
      - release-please
      - bump-lockfile
    runs-on: ubuntu-latest
    if: ${{ needs.release-please.outputs.releases-created && needs.release-please.outputs.package-name != 'minze-vscode' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main # needs to be explicitly set to pull the latest changes

      - name: Publish to npm
        uses: ./.github/actions/publish-npm
        with:
          node-version: ${{ env.NODE_VERSION }}
          package-name: ${{ needs.release-please.outputs.package-name }}
          npm-token: ${{ secrets.NPM_TOKEN }}

  publish-vs-marketplace:
    needs:
      - release-please
      - bump-lockfile
    runs-on: ubuntu-latest
    if: ${{ needs.release-please.outputs.releases-created && needs.release-please.outputs.package-name == 'minze-vscode' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main # needs to be explicitly set to pull the latest changes

      - name: Publish to VS Marketplace
        uses: ./.github/actions/publish-vs-marketplace
        with:
          node-version: ${{ env.NODE_VERSION }}
          package-name: ${{ needs.release-please.outputs.package-name }}
          vs-marketplace-token: ${{ secrets.VS_MARKETPLACE_TOKEN }}
