name: Test

on:
  pull_request:
    paths:
      - 'packages/**'
      - 'package.json'
      - '!packages/create-minze/template-**'
      - '!**/README.md'
  workflow_dispatch:

env:
  NODE_VERSION: 20
  PACKAGE_NAME: ${{ github.event.inputs.package }}

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tests
        uses: ./.github/actions/run-tests
        with:
          node-version: ${{ env.NODE_VERSION }}
